name: Build and Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('validator/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Run tests
        run: cargo test

      - name: Build packages
        run: just

      - name: Update package.json files
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          # For nodejs package
          cd pkg-nodejs
          jq --arg owner "$GITHUB_REPOSITORY_OWNER" \
             --arg repo "$GITHUB_REPOSITORY" \
             '.name = "@\($owner)/validators-nodejs" |
             .publishConfig = {"registry": "https://npm.pkg.github.com"} |
             .repository = {
                "type": "git",
                "url": "git+https://github.com/\($repo).git",
                "directory": "pkg-nodejs"
              }' package.json > temp.json && mv temp.json package.json

          # For bundler package
          cd ../pkg-bundler
          jq --arg owner "$GITHUB_REPOSITORY_OWNER" \
             --arg repo "$GITHUB_REPOSITORY" \
             '.name = "@\($owner)/validators-bundler" |
             .publishConfig = {"registry": "https://npm.pkg.github.com"} |
             .repository = {
                "type": "git",
                "url": "git+https://github.com/\($repo).git",
                "directory": "pkg-bundler"
              }' package.json > temp.json && mv temp.json package.json

      - name: Setup Node.js
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/setup-node@v4
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{ github.repository_owner }}"

      - name: Publish packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cd pkg-nodejs
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
          cd ../pkg-bundler
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
